### ISSUE TITLE
PHP 8.4 マニュアル翻訳状況

### ISSUE THREAD

**Issue by KentarouTakeda** [php/doc-ja#150]
英語版ドキュメントの次のIssueに掲載されたPull Requestの翻訳状況です:
* php/doc-en#3872

PHP 8.4向けに翻訳が必要なセクションの参考にしてください。

## 翻訳状況 一覧

* *`en`: 更新日: 2024-11-07 17:00*
* *`ja`: 更新日: 2024-11-07 17:00*

* [ ] php/doc-en#3465
  * *N/A*
* [ ] php/doc-en#3822
  * #146 @KentarouTakeda
* [ ] php/doc-en#3828
  * *N/A*
* [ ] php/doc-en#3874
  * *N/A*
* [ ] php/doc-en#3877
  * *N/A*
* [ ] php/doc-en#3878
  * *N/A*
* [ ] php/doc-en#3888
  * *N/A*
* [ ] php/doc-en#3894
  * *N/A*
* [ ] php/doc-en#3895
  * *N/A*
* [ ] php/doc-en#3896
  * *N/A*
* [ ] php/doc-en#3899
  * *N/A*
* [ ] php/doc-en#3900
  * *N/A*
* [ ] php/doc-en#3901
  * *N/A*
* [ ] php/doc-en#3906
  * *N/A*
* [ ] php/doc-en#3907
  * *N/A*
* [ ] php/doc-en#3909
  * *N/A*
* [ ] php/doc-en#3914
  * *N/A*
* [ ] php/doc-en#3922
  * *N/A*
* [ ] php/doc-en#3925
  * *N/A*
* [ ] php/doc-en#3956
  * *N/A*
* [ ] php/doc-en#3958
  * *N/A*
* [ ] php/doc-en#3959
  * *N/A*
* [ ] php/doc-en#3960
  * *N/A*
* [ ] php/doc-en#3962
  * *N/A*
* [ ] php/doc-en#3964
  * *N/A*
* [ ] php/doc-en#3965
  * *N/A*
* [x] php/doc-en#3972
  * #145 @Ippey
* [ ] php/doc-en#3975
  * *N/A*
* [ ] php/doc-en#3978
  * *N/A*
* [ ] php/doc-en#3990
  * *N/A*
* [ ] php/doc-en#3992
  * *N/A*
* [ ] php/doc-en#3993
  * *N/A*
* [ ] php/doc-en#4006
  * *N/A*
* [ ] php/doc-en#4007
  * *N/A*
* [ ] php/doc-en#4008
  * *N/A*

## 補足

* 英語版もまだ多くが完了していないため、このリストは随時追加される可能性があります。
* *SHOULD*: 英語版では、Pull Requestがマージされた後に別のコミットで新たな修正が入ることがあります。翻訳を行う際は *master* の最新を参照しているか確認をお勧めします。
* *MAY:* 時間を要する翻訳を開始する際は、他の人と作業が被らないよう、Issueやコメントで宣言すると良いかもしれません。

**Comment by jdkfx** [comment]
@KentarouTakeda 
https://github.com/php/doc-en/pull/3992 を取り込もうとしてたら、以下のファイルの翻訳が追いついていないようでしたのでこちらでファイルのblame見つつ翻訳追加していきます。
https://github.com/php/doc-en/blame/master/language-snippets.ent

**Comment by KentarouTakeda** [comment]
php/doc-en#3872 は現在更新されていないようなので [Milestone / PHP 8.4 / Closed](https://github.com/php/doc-en/milestone/6?closed=1) から最近の英語版の追加分を取得し、一覧を更新しました。

**Comment by KentarouTakeda** [comment]
難度の目安（私見）をアイコンにしました。
迷った際の着手の参考にしてください！

**Comment by KentarouTakeda** [comment]
@asumikam 
ありがとうございます。すみません、お手数おかけしました。
（マージに至らずとも、仕分けが進むだけで大助かりです！！）

**Comment by asumikam** [comment]
## PHPマニュアル翻訳のやりかた（忘備録）

### 事前に読む

- https://github.com/php/doc-ja/blob/master/CONTRIBUTING.md でお作法tipsを学ぶ
- OSSへのPRの作り方は調べるとわかりやすいのいっぱいでてきます🚀

### 対応する

- 対応する（`php-en` PRと呼びます）PRを決める
- `php-en` PRが最新の変更なのかを一応確認すると安心する
  - File Changedタブ > View file で`php-en` PRに積まれているcommitと一緒だよな、を確認すると良い
  - <img width="260" alt="スクリーンショット 2024-11-23 9 48 53" src="https://github.com/user-attachments/assets/a024a83c-500b-455f-af16-80be1c50467a">
- 翻訳作業をする
  - 基本的には比べっこして、追加修正ならブロックを適切な場所において日本語にする
    - https://github.com/php/doc-ja/blob/master/README_Glossary.md を読むとフムフムとなったりします
    - 「この単語（熟語）なんと訳してるんだろう・・・？」は、PHPマニュアルのenバージョンで同じものを探して、日本語マニュアルでなんと訳していそうかを調べたりしました
  - すでに日本語訳があるものもあります！その場合はメンションしてお知らせしましょう

### セルフレビュー（確認）する

- https://github.com/jdkfx/phpdoc を入れる
  - 画面で自分の修正

**Comment by Fendo181** [comment]
@asumikam さんが書いてくれた方法がわかりやすく、自分も翻訳参加できそうだと思ったのでPR用意します! 🙏 

こちらのPRを翻訳予定です。
https://github.com/php/doc-en/pull/3901

**Comment by SakiTakamachi** [comment]
BCMathは、原文がひと段落したら自分で翻訳書きます :)

**Comment by KentarouTakeda** [comment]
着手は数日後になってしまいそうですが php/doc-en#4115 は私が担当しようと思ってます。
（分量が膨大・DBは自分の専門分野）

**Comment by mumumu** [comment]
以下のシグネチャ系は私が担当します。

- https://github.com/php/doc-en/pull/4156
- https://github.com/php/doc-en/pull/4178
- https://github.com/php/doc-en/pull/4179
- https://github.com/php/doc-en/pull/4186
- https://github.com/php/doc-en/pull/4206
- https://github.com/php/doc-en/pull/4209

**Comment by Ippey** [comment]
↓頑張ります。

- https://github.com/php/doc-en/pull/4108

**Comment by siwa32** [comment]
php/doc-en#4083

こちらの作業致します

**Comment by siwa32** [comment]
- php/doc-en#4035
- php/doc-en#4102

コレ翻訳します

**Comment by siwa32** [comment]
1. php/doc-en#4037
2. php/doc-en#4244

こちらの取り込みをします。
2は上記リストにありませんが、1と修正されたファイルがかぶっているので一緒に行ってしまおうかと思います。

**Comment by siwa32** [comment]
php/doc-en#3872 から上記リストにないものを抜き出してみました。
機械的に抽出しただけで中身は見ていないので、抜け漏れや無関係な物が混じってしまっているかもしれません。

- [ ] php/doc-en#3799
  - N/A
- [ ] php/doc-en#3968
  - N/A
- [ ] php/doc-en#3974
  - N/A
- [ ] php/doc-en#4040
  - N/A
- [ ] php/doc-en#4207
  - N/A
- [ ] php/doc-en#4208
  - N/A
- [ ] php/doc-en#4220
  - N/A
- [ ] php/doc-en#4237
  - N/A
- [ ] php/doc-en#4238
  - N/A
- [ ] php/doc-en#4243
  - N/A
- [ ] php/doc-en#4245
  - N/A
- [ ] php/doc-en#4256
  - N/A
- [ ] php/doc-en#4257
  - N/A
- [ ] php/doc-en#4258
  - N/A
- [ ] php/doc-en#4259
  - N/A
- [ ] php/doc-en#4260
  - N/A
- [ ] php/doc-en#4262
  - N/A
- [ ] php/doc-en#4272
  - N/A
- [ ] php/doc-en#4281
  - N/A
- [ ] php/doc-en#4297
  - N/A
- [ ] php/doc-en#4306
  - N/A
- [ ] php/doc-en#4315
  - N/A
- [ ] php/doc-en#4316
  - N/A
- [ ] php/doc-en#4317
  - N/A
- [ ] php/doc-en#4318
  - N/A

**Comment by KentarouTakeda** [comment]
@siwa32 
ありがとうございます！私の方でも未確認なのですが 🆕 を付けてリストに反映させて頂きました。
（更新が追いついておらず申し訳ないです！）

**Comment by siwa32** [comment]
- php/doc-en#3974
- php/doc-en#3968

はプルリクではなくIssueでしたので、翻訳リストに含めなくてよいものでした。
上記のリストに対象外も混じってしまいました。失礼しました。

**Comment by SakiTakamachi** [comment]
https://github.com/php/doc-ja/pull/257

BCMath系まとめて全部です

**Comment by siwa32** [comment]
https://github.com/php/doc-en/issues/3872 にあって、上記リストに無い項目の追加分です。
すべて対象ファイルが1つで文章もそれほど長くはないので、🔰に分類されるかなーという所感です。

- [ ] php/doc-en#3799
  - *N/A*
- [ ] php/doc-en#4334
  - *N/A*
- [ ] php/doc-en#4335
  - *N/A*
- [ ] php/doc-en#4350
  - *N/A*
- [ ] php/doc-en#4351
  - *N/A*

**Comment by KentarouTakeda** [comment]
@siwa32 
ありがとうございます！大変助かります、そのまま反映させて頂きました！

**Comment by naopusyu** [comment]
以下は、https://github.com/php/doc-ja/pull/142 にて対応済みのようです (コミットはhttps://github.com/php/doc-ja/pull/142/commits/45691b01d7dec9d89eb06409cb56cff91482f3af)

> 🔰[add Zip::ER_TRUNCATED_ZIP doc-en#3799](https://github.com/php/doc-en/pull/3799)

**Comment by natsuki-engr** [comment]
以下は #263 で対応済みのようです！
> 🆕[[PHP 8.4] round() can throw a ValueError doc-en#4259](https://github.com/php/doc-en/pull/4259)

**Comment by mumumu** [comment]
curl および、8.4 で新規追加されたドキュメント以外は、全て最新に追随しました。

整理されていなかった進捗も整理した結果、2025/09/09 現在、未着手のものは下記のみになっています。

<img width="1121" height="792" alt="Image" src="https://github.com/user-attachments/assets/8fce3f09-21e4-4c22-8bb7-9f99bdc57f19" />
